# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

parameters:
- name: buildDirectory
  type: string

- name: releaseGroup
  type: string

- name: releaseReportCategory
  type: string
  default: ''

- name: blobPathPrefix
  type: string
  default: ''

- name: serverManifestCategory
  type: string
  default: prerelease

jobs:
  - job:
    displayName: Upload Release Reports
    variables:
    - group: storage-vars
    - name: version
      value: $[stageDependencies.build.build.outputs['SetVersion.version']]
    steps:
    - template: /tools/pipelines/templates/include-use-node-version.yml@self
    - template: /tools/pipelines/templates/include-install-build-tools.yml@self
      parameters:
        buildDirectory: ${{ parameters.buildDirectory }}

    - ${{ if eq(parameters.serverManifestCategory, 'prerelease') }}:
      - task: Bash@3
        displayName: Generate latest prerelease reports
        inputs:
          targetType: 'inline'
          workingDirectory: ${{ parameters.buildDirectory }}
          script: |
            set -eu -o pipefail
            mkdir generate_release_reports
            flub release report -g ${{ parameters.releaseGroup }} --releaseGroupOnly --useCurrentVersion -o generate_release_reports --baseFileName manifest

      - task: Bash@3
        displayName: Update prerelease report version
        inputs:
          targetType: 'inline'
          workingDirectory: ${{ parameters.buildDirectory }}
          script: |
            set -eu -o pipefail
            mkdir upload_release_reports
            flub release report-unreleased --version $(version) --fullReportFilePath generate_release_reports/manifest.full.json --outDir upload_release_reports --branchName '$(Build.SourceBranch)'

    - ${{ if eq(parameters.serverManifestCategory, 'release') }}:
      - task: Bash@3
        displayName: Generate release reports
        inputs:
          targetType: 'inline'
          workingDirectory: ${{ parameters.buildDirectory }}
          script: |
            set -eu -o pipefail
            mkdir generate_release_reports
            flub release report -g ${{ parameters.releaseGroup }} -o generate_release_reports --baseFileName manifest

      - task: Bash@3
        displayName: Update release report version
        inputs:
          targetType: 'inline'
          workingDirectory: ${{ parameters.buildDirectory }}
          script: |
            set -eu -o pipefail
            mkdir upload_release_reports
            flub release report-unreleased --version $(version) --fullReportFilePath generate_release_reports/manifest.full.json --outDir upload_release_reports --branchName '$(Build.SourceBranch)'

    - ${{ if ne(parameters.releaseReportCategory, '') }}:
      - task: Bash@3
        displayName: Rename release report files
        inputs:
          targetType: 'inline'
          workingDirectory: ${{ parameters.buildDirectory }}
          script: |
            set -eu -o pipefail
            for file in upload_release_reports/*.json; do
                if [ -f "$file" ]; then
                    mv "$file" "upload_release_reports/${{ parameters.releaseReportCategory }}$(basename "$file" .json)-$(Build.BuildNumber).json"
                fi
            done

    - template: /tools/pipelines/templates/include-upload-release-reports.yml@self
      parameters:
        buildDirectory: ${{ parameters.buildDirectory }}
        blobPathPrefix: ${{ parameters.blobPathPrefix }}
